Спринт номер 12
amdoit-git/PlaylistMaker pull request #5
Opened 2024-05-06 10:44 UTC by amdoit-git

Добавлен список истории поиска с сохранением в SharedPreferences
Добавлено переключение на светлую и темную тему из приложения

2024-05-06 17:42 UTC, DmitrijEgorow commented
![Screenshot_20240507_002555](https://github.com/amdoit-git/PlaylistMaker/assets/36837067/3568e920-f7a8-4a71-9b32-5831e429cd82)

- [ ] Если у устройства стоит увеличение текста, то наблюдается обрезка. Подробнее про вёрстку для таких случаев можно почитать [https://support.google.com/accessibility/android/answer/12159181](https://support.google.com/accessibility/android/answer/12159181)
- [ ] Цвет курсора должен быть светло-синим

2024-05-06 17:59 UTC, DmitrijEgorow requested changes

2024-05-06 17:59 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/App.kt
> +    var darkTheme: Boolean? = null;
Почему public? Так можно менять это поле в обход контракта – switchTheme

2024-05-06 17:59 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/MusicPlayer.kt
> +        fun startPlayOrStop(track: Track):Boolean{
Перед коммитом стоит приводить файлы к правильному стилю, так как код будут смотреть другие разработчики. В студии это легко делать путём вызова горячей комбинации клавиш (она зависит от ОС), её можно посмотреть в меню Code → Reformat Code

2024-05-06 17:59 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/MusicPlayer.kt
>                  //start()
Лучше не вливать закомментированный код в мастер

2024-05-06 17:59 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/SearchHistory.kt
> +    companion object {
companion обычно идёт в конце

Подробнее описано в [документации](https://kotlinlang.org/docs/coding-conventions.html#class-layout)

2024-05-06 17:59 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/SettingsActivity.kt
>              //startActivity(intent)
Аналогично

2024-05-06 17:59 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/SettingsActivity.kt
>          val b_user_agreement = findViewById<View>(R.id.button_user_agreement);
Нарушение code style

2024-05-06 17:59 UTC, DmitrijEgorow commented on app/src/main/res/layout/activity_search.xml
> +        android:id="@+id/tracksListTitle"
Другой стиль именования идентификаторов

2024-05-06 17:59 UTC, DmitrijEgorow commented on app/src/main/res/layout/activity_search.xml
> +                android:paddingEnd="14dp"
Лучше dimen

2024-05-06 17:59 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/FakeTracks.kt
Если этот файл больше не нужен, то его можно удалить

2024-05-06 17:59 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/MainActivity.kt
>      override fun onStop() {
Зачем переопределять?

2024-05-06 17:59 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/SearchTextField.kt
> +    private val activity: AppCompatActivity,
У активности свой ЖЦ
Зачем её передавать куда-то?

2024-05-06 17:59 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/SearchTextField.kt
> +    val editText: EditText,
Зачем передавать EditText?

2024-05-06 18:32 UTC, amdoit-git commented on app/src/main/java/com/example/playlistmaker/App.kt
> +    var darkTheme: Boolean? = null;
> Почему public? Так можно менять это поле в обход контракта – switchTheme
Первоначально программно выставлял позицию Switch на экране настроек в соответствии с этим полем. Потом сделал через стили, но забыл убрать. Сделал private

2024-05-06 18:33 UTC, amdoit-git commented on app/src/main/java/com/example/playlistmaker/MusicPlayer.kt
> +        fun startPlayOrStop(track: Track):Boolean{
> Перед коммитом стоит приводить файлы к правильному стилю, так как код будут смотреть другие разработчики. В студии это легко делать путём вызова горячей комбинации клавиш (она зависит от ОС), её можно посмотреть в меню Code → Reformat Code
Хорошо. Сделаю.

2024-05-06 18:33 UTC, amdoit-git commented on app/src/main/java/com/example/playlistmaker/MusicPlayer.kt
>                  //start()
> Лучше не вливать закомментированный код в мастер
Убрал

2024-05-06 18:34 UTC, amdoit-git commented on app/src/main/java/com/example/playlistmaker/SearchHistory.kt
> +    companion object {
> companion обычно идёт в конце
> 
> Подробнее описано в [документации](https://kotlinlang.org/docs/coding-conventions.html#class-layout)

Так тут целиком весь код в companion object. Кроме него вообще ничего нет.

2024-05-06 18:38 UTC, amdoit-git commented on app/src/main/res/layout/activity_search.xml
> +                android:paddingEnd="14dp"
> Лучше dimen
Нам говорили, что в dimen нужно выносить размеры которые используются многократно, а не только в одном месте. Их же так проще править?

2024-05-06 18:38 UTC, amdoit-git commented on app/src/main/java/com/example/playlistmaker/FakeTracks.kt
> Если этот файл больше не нужен, то его можно удалить

Удалил

2024-05-06 18:41 UTC, amdoit-git commented on app/src/main/java/com/example/playlistmaker/MainActivity.kt
>      override fun onStop() {
> Зачем переопределять?

Это я сделал воспроизведении трека при клике. И в данном месте кода плеер уничтожается, при выходе с экрана поиска по трекам на главный экран приложения.

2024-05-06 18:53 UTC, amdoit-git commented on app/src/main/java/com/example/playlistmaker/SearchTextField.kt
> +    private val activity: AppCompatActivity,
> У активности свой ЖЦ Зачем её передавать куда-то?

В этот класс я вынес логику работы текстового поля поиска по трекам, чтобы не загромождать код активити. В конструкторе класса ему передается ссылка на EditText, ссылка на кнопку для его очистки, ссылка на активити в которой находится этот EditText. Класс реализует появление крестика для очистки поля при непустом поле ввода. Очистку поля. Закрытие экранной клавиатуры. Activity нужно для закрытия клавиатуры. 
Ссылка на экземпляр SearchTextField есть только внутри этой самой активити, которая передается так что ситуация, что она останется после уничтожения активити исключена.

2024-05-06 18:53 UTC, amdoit-git commented on app/src/main/java/com/example/playlistmaker/SearchTextField.kt
> +    val editText: EditText,
> Зачем передавать EditText?
В этот класс я вынес логику работы текстового поля поиска по трекам, чтобы не загромождать код активити.

2024-05-06 18:54 UTC, amdoit-git commented
> ![Screenshot_20240507_002555](https://private-user-images.githubusercontent.com/36837067/328267602-3568e920-f7a8-4a71-9b32-5831e429cd82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMTkxMzUsIm5iZiI6MTcxNTAxODgzNSwicGF0aCI6Ii8zNjgzNzA2Ny8zMjgyNjc2MDItMzU2OGU5MjAtZjdhOC00YTcxLTliMzItNTgzMWU0MjljZDgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDE4MDcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzYjM5NTdiMTEwMTVhMGMxMWVmYmYxZmMwNDU1OThkNTk4NTU1NmEyYzkzNGU3ZTQ1YmM0MTM1OWZlMGU5NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f7BcGECTbeSu4jKkBLCWRt5jUtVrGI1wjDeHPPmcpWw)
> 
> * [ ]  Если у устройства стоит увеличение текста, то наблюдается обрезка. Подробнее про вёрстку для таких случаев можно почитать https://support.google.com/accessibility/android/answer/12159181
> * [ ]  Цвет курсора должен быть светло-синим
Спасибо. Сейчас буду изучать и исправлять

2024-05-06 19:18 UTC, amdoit-git commented on app/src/main/java/com/example/playlistmaker/SearchTextField.kt
> +    val editText: EditText,
Тоже надо сделать EditText приватным. Вся логика внутри класса и доступ извне к нему не нужен.

2024-05-07 17:12 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/MainActivity.kt
>      override fun onStop() {
onStop и onDestroy имеют только логи внутри себя

2024-05-08 07:08 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/SearchHistory.kt
> +    companion object {
В таком случае подход ещё подозрительнее
Функции в companion не будут унаследованы, соответственно расширение класса SearchHistory будет бессмысленным. Возникают связанные с этим же фактом проблемы с тестированием и мокированием чего-то для SearchHistory.
И можно проговорить про минусы статических (вложенных) классов, в которые это всё компилируется
Всё это относится и к MusicPlayer

2024-05-10 17:05 UTC, merged